//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されたものです。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
	public partial class CheckIn
	{
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		protected global::System.Web.UI.WebControls.Panel pnlSuccess;

		protected global::System.Web.UI.WebControls.Label lblSuccess;

		protected global::System.Web.UI.WebControls.Panel pnlError;

		protected global::System.Web.UI.WebControls.Label lblError;

		protected global::System.Web.UI.WebControls.Panel pnlNewGuest;

		protected global::System.Web.UI.WebControls.Button btnSelectNew;

		protected global::System.Web.UI.WebControls.Panel pnlExistingGuest;

		protected global::System.Web.UI.WebControls.Button btnSelectExisting;

		protected global::System.Web.UI.WebControls.Panel pnlNewGuestForm;

		protected global::System.Web.UI.WebControls.TextBox txtLastName;

		protected global::System.Web.UI.WebControls.TextBox txtFirstName;

		protected global::System.Web.UI.WebControls.TextBox txtEmail;

		protected global::System.Web.UI.WebControls.TextBox txtPhone;

		protected global::System.Web.UI.WebControls.TextBox txtIDNumber;

		protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;

		protected global::System.Web.UI.WebControls.Panel pnlExistingGuestForm;

		protected global::System.Web.UI.WebControls.DropDownList ddlGuest;

		protected global::System.Web.UI.WebControls.Panel pnlRoomSection;

		protected global::System.Web.UI.WebControls.DropDownList ddlRoom;

		protected global::System.Web.UI.WebControls.TextBox txtNights;

		protected global::System.Web.UI.WebControls.TextBox txtNumberOfGuests;

		protected global::System.Web.UI.WebControls.TextBox txtCheckOut;

		protected global::System.Web.UI.WebControls.Label lblTotalAmount;

		protected global::System.Web.UI.WebControls.Button btnCancel;

		protected global::System.Web.UI.WebControls.Button btnCheckIn;
	}
}